spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}

payment:
  stripe:
    api-key: ${STRIPE_SECRET_KEY}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET}
  razorpay:
    key-id: ${RAZORPAY_KEY_ID}
    key-secret: ${RAZORPAY_KEY_SECRET}
    webhook-secret: ${RAZORPAY_WEBHOOK_SECRET}

logging:
  level:
    root: WARN
    com.tcon.financial: INFO
